name: Cypress Tests

on:
  push:
    branches:
      - testes

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Server BackEnd
        run: |
          cd server
          npm install
          nohup npm start &
          until curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q "200"; do
            echo "Waiting for backend to start..."
            sleep 1
          done
          echo "Backend is running successfully."

      - name: Start Web App FrontEnd
        run: |
          cd web
          npm install
          nohup npm start &
          until curl -s http://localhost:3000 | grep -q "<title>"; do
            echo "Waiting for web app to start..."
            sleep 1
          done
          echo "Frontend is running successfully."

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
              wait-on: 'http://localhost:3000,http://localhost:8080'
