name: Cypress Tests

on:
  push:
    branches:
      - testes

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Server BackEnd
        run: |
          cd server
          npm install
          nohup npm start &
          timeout=60
          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q "200"; do
          echo "Waiting for backend to start..."
          timeout=$((timeout - 1))
          if [ $timeout -le 0 ]; then
          echo "Backend failed to start within the expected time."
          exit 1
          fi
          sleep 1
          done
          echo "Backend is running successfully."

      - name: Start Web App FrontEnd
        run: |
          cd web
          npm install
          nohup npm start &
          timeout=60
          while ! curl -s http://localhost:3000 | grep -q "<title>"; do
          echo "Waiting for web app to start..."
          timeout=$((timeout - 1))
          if [ $timeout -le 0 ]; then
          echo "Frontend failed to start within the expected time."
          exit 1
          fi
          sleep 1
          done
          echo "Frontend is running successfully."
          curl -s http://localhost:3000 # Added for additional logging
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/cadastro-sucesso.cy.js
            cypress/e2e/dashboard.cy.js
          wait-on: 'http://localhost:3000,http://localhost:8080'
          record: true
        env: 
          CYPRESS_RECORDD_KEY: ${{ secrets.CYPRESS_RECORDD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}